heat_template_version: 2015-10-15
description: Launch a OpenShift Container Platform cluster 3.5 with RHEL7

parameters:
  PARTITION:
    type: number
    description: Execute partitioning in an extra partion in vda
    default: "1"
  USER:
    type: string
    description: User to authenticate in RHEL subscription-manager
  PASS:
    type: string
    description: Password to authenticate in RHEL subscription-manager
  POOLID:
    type: string
    description: Execute partitioning in an extra partion in vda
    default: "1"
  VOL:
    type: string
    description: Name of the volume group
    default: "docker-vg"
  HTUSER:
    type: string
    description: Apache HTPasswd authentication regular user
  HTPASS:
    type: string
    description: Apache HTPasswd authentication regular user password
  HTADMINPASS:
    type: string
    description: Apache HTPasswd authentication admin user password

resources:
  ocp35:
    type: OS::Nova::Server
    properties:
      name: ocp35
      availability_zone: nova:node2.cbyg.marcote.org
      image: rhel7lvm
      flavor: osmaster
      key_name: osdefault
      personality: {/root/ocp35-cfg.yml: {get_file: /home/gonzalo/Development/openshift-heat/ocp35-cfg.yml}}
      networks:
        - port: 8607db68-20b7-4db5-ab1a-545c346ba9da
        - port: {get_resource: ocp35_port}
      user_data:
        str_replace:
          template: {get_file: ocp35-master-install.sh}
          params:
            $PARTITION: {get_param: PARTITION}
            $USER: {get_param: USER}
            $PASS: {get_param: PASS}
            $POOLID: {get_param: POOLID}
            $VOL: {get_param: VOL}
            $HTUSER: {get_param: HTUSER}
            $HTPASS: {get_param: HTPASS}
            $HTADMINPASS: {get_param: HTADMINPASS}
            $CONFIG: {get_file: ocp35-cfg.yml}

  ocp35_port:
    type: OS::Neutron::Port
    properties:
      network: selfservice
      security_groups:
        - 74400bd4-ad90-47bd-923c-0723d517a228
        - ssh-internet
        - osmaster

  ocp35node1:
    type: OS::Nova::Server
    properties:
      name: ocp35node1
      availability_zone: nova:node1.cbyg.marcote.org
      image: rhel7lvm
      flavor: osnode
      personality: {/root/ocp35-cfg.yml: {get_file: /home/gonzalo/Development/openshift-heat/ocp35-cfg.yml}}
      key_name: osdefault
      networks:
        - port: f52de966-4085-4289-98ed-af2ab549054c
        - port: {get_resource: ocp35node1_port}
      user_data:
        str_replace:
          template: {get_file: ocp35-node-install.sh}
          params:
            $PARTITION: {get_param: PARTITION}
            $USER: {get_param: USER}
            $PASS: {get_param: PASS}
            $POOLID: {get_param: POOLID}
            $VOL: {get_param: VOL}

  ocp35node1_port:
    type: OS::Neutron::Port
    properties:
      network: selfservice
      security_groups:
        - 74400bd4-ad90-47bd-923c-0723d517a228
        - ssh-internet
        - osnode

  ocp35node2:
    type: OS::Nova::Server
    properties:
      name: ocp35node2
      availability_zone: nova:node1.cbyg.marcote.org
      image: rhel7lvm
      flavor: osnode
      personality: {/root/ocp35-cfg.yml: {get_file: /home/gonzalo/Development/openshift-heat/ocp35-cfg.yml}}
      key_name: osdefault
      networks:
        - port: 0ab1aec8-6518-4e2f-8cb8-34ed2babc02d
        - port: {get_resource: ocp35node2_port}
      user_data:
        str_replace:
          template: {get_file: ocp35-node-install.sh}
          params:
            $PARTITION: {get_param: PARTITION}
            $USER: {get_param: USER}
            $PASS: {get_param: PASS}
            $POOLID: {get_param: POOLID}
            $VOL: {get_param: VOL}

  ocp35node2_port:
    type: OS::Neutron::Port
    properties:
      network: selfservice
      security_groups:
        - 74400bd4-ad90-47bd-923c-0723d517a228
        - ssh-internet
        - osnode

outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ ocp35, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ ocp35, first_address ] }
