heat_template_version: 2015-10-15
description: Launch a OpenShift Container Platform cluster 3.5 with RHEL7

parameters:
  INSTALL:
    type: string
    description: Quick or Advance installation

resources:
  ocp35:
    type: OS::Nova::Server
    properties:
      name: ocp35
      availability_zone: nova:node2.cbyg.marcote.org
      image: rhel7lvm
      flavor: osmaster
      key_name: osdefault
      networks:
        - port: 8607db68-20b7-4db5-ab1a-545c346ba9da
        - port: {get_resource: ocp35_port}
      personality: {"/home/cloud-user/ocp35.sh": {get_file: "/home/gonzalo/Development/openshift-heat/ocp35.sh"}}
      personality: {"/root/.ssh/id_rsa": {get_file: "/home/gonzalo/.ssh/osdefault"}}
      user_data:
        str_replace:
          template: {get_file: lvm_metadata.sh}
          params:
            $FOO: {get_param: INSTALL}

  ocp35_port:
    type: OS::Neutron::Port
    properties:
      network: selfservice
      security_groups:
        - 74400bd4-ad90-47bd-923c-0723d517a228
        - ssh-internet
        - osmaster

  ocp35node1:
    type: OS::Nova::Server
    properties:
      name: ocp35node1
      availability_zone: nova:node1.cbyg.marcote.org
      image: rhel7lvm
      flavor: osnode
      key_name: osdefault
      networks:
        - port: f52de966-4085-4289-98ed-af2ab549054c
        - port: {get_resource: ocp35node1_port}
      personality: {"/home/cloud-user/ocp35.sh": {get_file: "/home/gonzalo/Development/openshift-heat/ocp35.sh"}}
      user_data:
        str_replace:
          template: {get_file: lvm_metadata.sh}
          params:
            $FOO: {get_param: INSTALL}

  ocp35node1_port:
    type: OS::Neutron::Port
    properties:
      network: selfservice
      security_groups:
        - 74400bd4-ad90-47bd-923c-0723d517a228
        - ssh-internet
        - osnode

  ocp35node2:
    type: OS::Nova::Server
    properties:
      name: ocp35node2
      availability_zone: nova:node1.cbyg.marcote.org
      image: rhel7lvm
      flavor: osnode
      key_name: osdefault
      networks:
        - port: 0ab1aec8-6518-4e2f-8cb8-34ed2babc02d
        - port: {get_resource: ocp35node2_port}
      personality: {"/home/cloud-user/ocp35.sh": {get_file: "/home/gonzalo/Development/openshift-heat/ocp35.sh"}}
      user_data:
        str_replace:
          template: {get_file: lvm_metadata.sh}
          params:
            $VOL: docker-vg

  ocp35node2_port:
    type: OS::Neutron::Port
    properties:
      network: selfservice
      security_groups:
        - 74400bd4-ad90-47bd-923c-0723d517a228
        - ssh-internet
        - osnode

outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ ocp35, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ ocp35, first_address ] }
