heat_template_version: 2015-10-15
description: Launch a OpenShift cluster with RHEL Atomic image using ``medium`` flavor, ``osdefault`` key, and one provider network.

parameters:
  NetID:
    type: string
    description: Network ID to use for the instance.

resources:
  ocpmaster:
    type: OS::Nova::Server
    properties:
      image: rhel-atomic-7.4.3
      flavor: medium
      key_name: osdefault
      networks:
      - network: { get_param: NetID }

  ocpnode1:
    type: OS::Nova::Server
    properties:
      image: rhel-atomic-7.4.3
      flavor: small
      key_name: osdefault
      networks:
      - network: { get_param: NetID }

  ocpnode2:
    type: OS::Nova::Server
    properties:
      image: rhel-atomic-7.4.3
      flavor: small
      key_name: osdefault
      networks:
      - network: { get_param: NetID }

outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ ocpmaster, name ] }
    value: { get_attr: [ ocpnode1, name ] }
    value: { get_attr: [ ocpnode2, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ ocpmaster, first_address ] }
    value: { get_attr: [ ocpnode1, first_address ] }
    value: { get_attr: [ ocpnode2, first_address ] }
