heat_template_version: 2015-10-15
description: Launch a OpenShift cluster with RHEL Atomic image using ``medium`` flavor, ``osdefault`` key, and one provider network.

parameters:
  NetID:
    type: string
    description: Network ID to use for the instance.

resources:
  ocpmaster:
    type: OS::Nova::Server
    properties:
      name: ocpmaster
      availability_zone: nova:node2.cbyg.marcote.org
      image: rhel-7.4
      flavor: medium
      key_name: osdefault
      networks:
      - network: { get_param: NetID }
      security_groups:
      - 74400bd4-ad90-47bd-923c-0723d517a228
      - ssh-external
      - osmaster

  ocpnode1:
    type: OS::Nova::Server
    properties:
      name: ocpnode1
      availability_zone: nova:node1.cbyg.marcote.org
      image: rhel-7.4
      flavor: small
      key_name: osdefault
      networks:
      - network: { get_param: NetID }
      security_groups:
      - 74400bd4-ad90-47bd-923c-0723d517a228
      - ssh-external
      - osnode

  ocpnode2:
    type: OS::Nova::Server
    properties:
      name: ocpnode2
      availability_zone: nova:node1.cbyg.marcote.org
      image: rhel-7.4
      flavor: small
      key_name: osdefault
      networks:
      - network: { get_param: NetID }
      security_groups:
      - 74400bd4-ad90-47bd-923c-0723d517a228
      - ssh-external
      - osnode

outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ ocpmaster, name ] }
    value: { get_attr: [ ocpnode1, name ] }
    value: { get_attr: [ ocpnode2, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ ocpmaster, first_address ] }
    value: { get_attr: [ ocpnode1, first_address ] }
    value: { get_attr: [ ocpnode2, first_address ] }
