heat_template_version: 2015-10-15
description: Launch a OpenShift cluster 3.7 with RHEL7

parameters:
  INSTALL:
    type: string
    description: Quick or Advance installation

resources:
  ose37:
    type: OS::Nova::Server
    properties:
      name: ose37
      availability_zone: nova:node2.cbyg.marcote.org
      image: rhel7lvm
      flavor: osmaster
      key_name: osdefault
      networks:
        - port: ...
        - port: {get_resource: ose37_port}
      personality: {/root/ose37.sh: {get_file: "./ose37.sh"}}
      user_data:
        str_replace:
          template: {get_file: lvm_metadata.sh}
          params:
            $FOO: {get_param: INSTALL}

  ose37_port:
    type: OS::Neutron::Port
    properties:
      network: selfservice
      security_groups:
        - 74400bd4-ad90-47bd-923c-0723d517a228
        - ssh-external
        - osmaster

  ose37node1:
    type: OS::Nova::Server
    properties:
      name: ose37node1
      availability_zone: nova:node1.cbyg.marcote.org
      image: rhel7lvm
      flavor: osnode
      key_name: osdefault
      networks:
        - port: ...
        - port: {get_resource: ose37node1_port}
      personality: {/root/ose37.sh: {get_file: "./ose37.sh"}}
      user_data:
        str_replace:
          template: {get_file: lvm_metadata.sh}
          params:
            $FOO: {get_param: INSTALL}

  ose37node1_port:
    type: OS::Neutron::Port
    properties:
      network: selfservice
      security_groups:
        - 74400bd4-ad90-47bd-923c-0723d517a228
        - ssh-external
        - osmaster

  ose37node2:
    type: OS::Nova::Server
    properties:
      name: ose37node2
      availability_zone: nova:node1.cbyg.marcote.org
      image: rhel7lvm
      flavor: osnode
      key_name: osdefault
      networks:
      - port: ...
      - port: {get_resource: ose37node2_port}
      personality: {/root/ose37.sh: {get_file: "./ose37.sh"}}
      user_data:
        str_replace:
          template: {get_file: lvm_metadata.sh}
          params:
            $VOL: docker-vg

  ose37node2_port:
    type: OS::Neutron::Port
    properties:
      network: selfservice
      security_groups:
        - 74400bd4-ad90-47bd-923c-0723d517a228
        - ssh-external
        - osmaster

outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ ose37, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ ose37, first_address ] }
